### ISSUE TITLE
Error: <svg> attribute width: Expected length, "undefined"

### ISSUE THREAD

**Issue by Dara-To** [chenqingspring/react-lottie#115]
Not sure what's going on here. I used the same lottie file from another project and same code but got these errors.

I am able to render the animation but keeping errors in the console is not acceptable.

<img width="393" alt="Screen Shot 2020-05-28 at 4 50 15 PM" src="https://user-images.githubusercontent.com/33760969/83193356-dd1fa080-a104-11ea-89af-f0b744bdab54.png">

`<Loader width={330} height={400} />`

```
import React from "react"
import Lottie from "rangel-react-lottie"
import styled from "styled-components"

import animationData from "../../lotties/icons/logo-animation.json"

const Loader = props => {
  const { isLoading, width, height } = props

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  }

  return (
    <Container>
      <Lottie options={defaultOptions} width={width} height={height} isStopped={!isLoading} />
    </Container>
  )
}

export default Loader
```

**Comment by LaVielle** [comment]
For those of you landing here now, this issue is cause by wrongly importing `animationData` from the json file.

In the README example, replace:
```JavaScript
- import * as animationData from './pinjump.json'
```
```JavaScript
+ import animationData from './pinjump.json'
```

**Comment by thanh90** [comment]
something really fun here is **import * as animationData** actually working on my web page but not in storybook. so i had to change to **import * as animationData**

**Comment by Monte47** [comment]
The above does not help me. This is my full code.

```
import React, { useEffect } from 'react'
import lottie from 'lottie-web'
import animationData from '../assets/lottie/Icon-heart_green.json'
// import animationData from '../assets/lottie/loading.json'

type LottieProps = {
  readonly source: unknown
  readonly height?: number | string
  readonly width?: number | string
  readonly loop?: boolean
  readonly speed?: number
  readonly onAnimationStart?: () => void | null
  readonly onAnimationFinish?: () => void | null
}

const Lottie = () => {
  useEffect(() => {
    lottie.loadAnimation({
      container: document.querySelector('#lottie-element'),
      renderer: 'svg',
      loop: true,
      autoplay: true,
      animationData,
      rendererSettings: {
        preserveAspectRatio: 'xMidYMid slice',
      },
    })
  }, [])

  return (
    <div>
      <div style={{ height: 200, width: 200 }} id="lottie-element" />
    </div>
  )
}
```

error is:
![image](https://user-images.githubusercontent.com/21068946/128262096-517e03dc-cf27-4a00-87d5-06cbbd283851.png)

when I use the other animation (the one that is currently commented out) it works fine.

**Comment by albe68** [comment]
I know I'm supposed to talk about other package here . But I got the same <svg> error in Razor Pay Package Node implementation.

**Comment by ompupul** [comment]
hy did you solved it????

**Comment by JonatasSilva01** [comment]
verifica se os atributos ou as tags estão certas talvez seja algo do em volta do contexto tive um problema semelhante a esse e o que me ajudou foi analisar os atributos que podem ter vindo sem informações pra vcs
