### ISSUE TITLE
What does progressiveLoad setting actually do?

### ISSUE THREAD

**Issue by rarehunter** [chenqingspring/react-lottie#127]
I am using react-lottie to display animations on a page but also want to lazily load them as the animations are below the initial viewport.  I discovered the `progressiveLoad` renderer setting but am wondering what it is actually supposed to achieve.

```
import React from 'react'
import Lottie from 'react-lottie'

const HomePage = () => {
    const animationStyle = {
        // styles here
    }

    const animationOptions = {
        loop: false,
        autoplay: false,
        renderer: 'svg',
        path: 'https://somepath.net/to/a/CDN/resource/animation.json',
        rendererSettings: {
            progressiveLoad: true,
        },
    }

    return (
        <div>
            {* Other stuff here *}
            <Lottie style={animationStyle} options={animationOptions} />
        </div>
    )
}
```

Now, if I open the Network tab of my browser developer tools and visit the page, I see the `animation.json` being fetched upon rendering the page. Since I have `progressiveLoad` turned on, I would expect to NOT see it fetched upon rendering the page but rather fetched when I scroll near where the component is actually be used.

Now this may be a misunderstanding of how the `progressiveLoading` setting works but can somewhat illuminate to me what is going on here and how I can achieve what I ultimately want which is a deferred loading of the resource?

**Comment by mabdullahz** [comment]
@rarehunter @NeversSync
`progressiveLoad` is not meant to do that. Rather, given a relatively long animation it progressively adds SVG markup instead of all at once, improving initial load time for the animation. ([Reference](https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#progressiveload))
For deferring resource fetch from CDN, you would have to configure [output.publicpath](https://webpack.js.org/configuration/output/#outputpublicpath) property in webpack (haven't tried this out myself)

**Comment by rarehunter** [comment]
@mabdullahz Thanks! Then this was a misunderstanding on my part.

**Comment by ivanjeremic** [comment]
> @rarehunter @NeversSync `progressiveLoad` is not meant to do that. Rather, given a relatively long animation it progressively adds SVG markup instead of all at once, improving initial load time for the animation. ([Reference](https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#progressiveload)) For deferring resource fetch from CDN, you would have to configure [output.publicpath](https://webpack.js.org/configuration/output/#outputpublicpath) property in webpack (haven't tried this out myself)

The trick with public path is interesting, wonder if anyone has ever done this, basically what I want is fetch the needed images as the the animation progresses.
