### ISSUE TITLE
Cursor turns to pointer when hovering over <Lottie>, how to set cursor style?

### ISSUE THREAD

**Issue by ValerieKC** [chenqingspring/react-lottie#163]
Description:
When hovering over the <Lottie> component, the cursor always turns into a pointer. I would like to know if there is a way to customize the cursor style for the <Lottie> component.

Steps to Reproduce:

Add a <Lottie> component to the page.
Hover over the <Lottie> component.
Notice that the cursor turns into a pointer.
Expected Behavior:
The cursor should not change to a pointer unless specifically set.

Actual Behavior:
The cursor changes to a pointer when hovering over the <Lottie> component.

Environment:

I use React18

Thank you for your assistance!

**Comment by fnielson1** [comment]
<Lottie style={{cursor: 'pointer' /*or whatever cursor type you want*/}} />

**Comment by ValerieKC** [comment]
Wow! It's that simple! Thank you!

**Comment by fnielson1** [comment]
You're welcome!
