### ISSUE TITLE
Request to update babel-runtime library to latest version

### ISSUE THREAD

**Issue by chandruapk** [chenqingspring/react-lottie#166]
Hi Team,

Can you please update all your depedency packages to latest version. Particularly babel-runtime library. We are getting Security vulnerability error for core-js which is dependency package of babel-runtime library. Thanks.

**Comment by chenqingspring** [comment]
@chandruapk latest version of babel-runtime is updated in v1.2.8

**Comment by muermaru** [comment]
after this update, i got an error when building my project, it seem to be a babel-runtime error

✖ Errors: 

[7mresolve 'babel-runtime/helpers/extends' in 'xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules/react-lottie/dist'[27m
  Parsed request is a module
  using description file: xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules/react-lottie/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules/react-lottie/dist/node_modules doesn't exist or is not a directory
      xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules/react-lottie/node_modules doesn't exist or is not a directory
      xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules
        xxx/node_modules/.pnpm/react-lottie@1.2.8_react@18.3.1/node_modules/babel-runtime doesn't exist
      looking for modules in xxx/node_modules/.pnpm/node_modules
        xxx/node_modules/.pnpm/node_modules/babel-runtime doesn't exist
      xxx/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in xxx/node_modules
        xxx/node_modules/babel-runtime doesn't exist
      /home/gitlab-runner/builds/Sfx2kxgV/1/fcq/fcbip/data-analysis/node_modules doesn't exist or is not a directory
      /home/gitlab-runner/builds/Sfx2kxgV/1/fcq/fcbip/node_modules doesn't exist or is not a directory
      /home/gitlab-runner/builds/Sfx2kxgV/1/fcq/node_modules doesn't exist or is not a directory
      /home/gitlab-runner/builds/Sfx2kxgV/1/node_modules doesn't exist or is not a directory
      /home/gitlab-runner/builds/Sfx2kxgV/node_modules doesn't exist or is not a directory
      /home/gitlab-runner/builds/node_modules doesn't exist or is not a directory
      /home/gitlab-runner/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

**Comment by chenqingspring** [comment]
@chandruapk @babel/runtime is removed in v1.2.9

**Comment by ibakirov** [comment]
@chenqingspring version v1.2.8 and on-wards is broken without babel-runtime

**Comment by chandruapk** [comment]
Hi  Chen Qing,

Thanks for the update. Appreciate your support.

Regards,
Chandru P
