### ISSUE TITLE
TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by xinxinhe1810** [chenqingspring/react-lottie#51]
Cannot read property 'destroy' of undefined
`    value: function destroy() {
      this.anim.destroy();
    }`

**Comment by luskin** [comment]
This is a problem introduced with `react-scripts ^2.0.0` - if you downgrade to `1` it works. We need to find a solution for this though because I am forced to use`2.0.4` here.

**Comment by luskin** [comment]
as a workaround I discovered you can do the following:

```
const defaultOptions = {
      loop: true,
      autoplay: true,
      animationData: require('./Assets/searchAnimation.json'),
      rendererSettings: {
        preserveAspectRatio: 'xMidYMid slice',
      },
    }

...


<Lottie options={defaultOptions} height={240} width={'75%'} />
```

**Comment by mcdappdev** [comment]
@luskin I just discovered that `import animationData from './animation.json'` also works (minus the `* as`)

**Comment by karahan** [comment]
Yo @mcdappdev this also worked, thanks dude

**Comment by mohitp22** [comment]
@mcdappdev it worked for me as well, thanks alot

**Comment by php7webmob** [comment]
worked for me. please close this issue.

**Comment by gihan-onramper** [comment]
I am still getting the same error. Even after I tried the above workaround. Any update on this ?

**Comment by AlbertBrahimi** [comment]
any update on this one guys? 
still facing it

**Comment by AlbertBrahimi** [comment]
Hey guys anyone still facing this issue, in react, i found a way, 
wrap the component with React.memo, and then send animation data as a prop.In my case i think the issue was related to many renders,  in reload this issue wasn't present. 
 This one worked for me.
