### ISSUE TITLE
TypeError: Cannot set property 'fillStyle' of null

### ISSUE THREAD

**Issue by eliasrodeloso** [chenqingspring/react-lottie#66]
Hey guys

First of all, thanks for your job with this, is really amazing and easy to use

I'm having this issue when I'm trying to test a component where I'm using `react-lottie`, also, keep in mind that this is happening when jest is trying to import Lottie. This is my component:

```javascript
MyComponent.js

import React from 'react';
import Lottie from 'react-lottie';
mport loaderAnimation from './loaderData.json';
import profileAnimation from './profileData.json';

class AnimatedImages extends PureComponent {
  getAnimationData = () => {
    const { image } = this.props;
    switch (image) {
      case 'loader':
        return loaderAnimation;

      case 'profile':
        return profileAnimation;

      default:
        return loaderAnimation;
    }
  };

  render() {
    const { loop } = this.props;
    return (
      <div className="loader-wrapper">
        <Lottie
          options={{
            animationData: this.getAnimationData(),
            loop,
            autoplay: true
          }}
        />
      </div>
    );
  }
}

```

And my test file
```javascript
MyComponent.spec.js

import React from 'react';
import { shallow, mount } from 'enzyme';
import MyComponent from './MyComponent';

jest.mock('lottie-web'); // I have tried mock the animation data, nothing
jest.mock('react-lottie');

describe('Animated images component', () => {
  it('should render with crashing', () => {
    const component = shallow(<AnimatedImages />); // I have tried it with mount, but nothing
    expect(component).toBeDefined();
  });
});

```

Once I run the test I got the error mentioned above and I'm not able to test the component properly. 
It will be great if you guys mention, _if I'm doing something wrong_, in your documentation the proper way to do unit tests for the components made with `react-lottie`. I saw your code and I notice that you have a test file, but I think is not very accurate for this particular case.

Let me know, if I'm doing something wrong, if not, I think that this is probably a bug for the component.

Thank you guys in advance!

**Comment by eliasrodeloso** [comment]
UPDATE: I solved the problem, it wasn't a bug, is a bad configuration issue: there is to add the `canvas` element to Jest, remember that Jest uses `jsdom`. I realized that, once I stopped trying to test the component and try to find and workaround for the other components and the console showed me the actual error:

```sh
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
        at module.exports ...
```

So to solve it, what I did was install [`jest-canvas-mock` library](https://github.com/hustcc/jest-canvas-mock), once installed I went to my `setupTest.js` and imported it globally. Probably I will make a PR with this info for the documentation.

Hopefully this will help some one else in the future.

**Comment by wpp** [comment]
Thank you very much for sharing @eliasrodeloso! I ran into the same issue and solved it with the jest-canvas-mock library too.

**Comment by thakuranujsingh** [comment]
Hi, I am facing this issue, when I am writing the unit test case, could you help me how I fix this?

TypeError: Cannot set property 'fillStyle' of null

      1 | import React from "react";
    > 2 | import Lottie from "react-lottie";
        | ^
      3 | import tickAnimationData from "../../constant/tickAnimationData.json";
      4 |
      5 | export const TickAnimationIcon: React.FC = () => {

      at ../../node_modules/lottie-web/build/player/lottie.js:4171:23
      at ../../node_modules/lottie-web/build/player/lottie.js:4174:6
      at ../../node_modules/lottie-web/build/player/lottie.js:4274:2
      at ../../node_modules/lottie-web/build/player/lottie.js:7:26
      at Object.<anonymous> (../../node_modules/lottie-web/build/player/lottie.js:12:2)
      at Object.<anonymous> (../../node_modules/react-lottie/dist/index.js:39:18)
      at Object.<anonymous> (src/components/uiComponents/TickAnimatedIcon.tsx:2:1)
      at Object.<anonymous> (src/components/Modal/FinaliseFormModal.tsx:16:1)

**Comment by crysfelinvision** [comment]
Got the same issues but it was fixed by installed `jest-canvas-mock` as suggested by @eliasrodeloso eliasrodeloso

**Comment by gerhat** [comment]
@eliasrodeloso thanks for sharing!

**Comment by afsanefda** [comment]
> UPDATE: I solved the problem, it wasn't a bug, is a bad configuration issue: there is to add the `canvas` element to Jest, remember that Jest uses `jsdom`. I realized that, once I stopped trying to test the component and try to find and workaround for the other components and the console showed me the actual error:
> 
> ```shell
> console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
>     Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
>         at module.exports ...
> ```
> 
> So to solve it, what I did was install [`jest-canvas-mock` library](https://github.com/hustcc/jest-canvas-mock), once installed I went to my `setupTest.js` and imported it globally. Probably I will make a PR with this info for the documentation.
> 
> Hopefully this will help some one else in the future.

Could you please share the setting ?

**Comment by adarshyadav777** [comment]
Got the same issues but it was fixed by installing jest-canvas-mock as suggested by @eliasrodeloso ,thankyou so much.
